### ISSUE TITLE
Issue with running script with 5120x2880

### ISSUE THREAD

**Issue by malroy** [stevenbenner/interfacelift-downloader#13]
Hi Steven,

I try running the script and every single time , it has this error below

interfacelift-downloader 5120x2880 /Downloads/5120x2880
InterfaceLIFT Wallpaper Auto-Downloader

Searching pages for images...
(The download will begin after the page scan finishes.)
Scanning Page 1...
Scanning Page 2...
Scanning Page 3...
Scanning Page 4...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

**Comment by stevenbenner** [comment]
Closing issue because there has been no response for some time.
