### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by ghost** [stevenbenner/interfacelift-downloader#14]
Hello, I use your interfacelift downloader since June and I never have problem with it.

Can you help me use it again?

Error that I have:

"Searching pages for images...
(The download will begin after the page scan finishes.)
Scanning Page 1...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)"

**Comment by stevenbenner** [comment]
I cannot reproduce this issue. The error seems to indicate that it could not resolve the host name for the site. Are you running on a proxy or tor? Or using any custom/unusual internet settings?

**Comment by stevenbenner** [comment]
Closing issue because there has been no response for some time.
