### ISSUE TITLE
Add support for iPhone 6 Plus resolution (1242x2208)

### ISSUE THREAD

**Issue by xvagosx** [stevenbenner/interfacelift-downloader#18]
Pretty descriptive title: please add support for iPhone 6 Plus resolution (1242x2208).

**Comment by stevenbenner** [comment]
Added the iphone resolutions in commit 9770a1e185b21bcc78f6bd86a0aea3c69ca37599.

This will be included in the next release.

**Comment by stevenbenner** [comment]
This as been published to npm with version 2.3.0.
