### ISSUE TITLE
Refactor Downloader() to fix or remove recursion.

### ISSUE THREAD

**Issue by stevenbenner** [stevenbenner/interfacelift-downloader#9]
Right now the `Downloader()` object uses recursion to iterate through the list. This is problematic because it will lead to a very large call stack unless you use a `setImmediate()` to break out of it (see: commit 747ce133f08bae4c637a74e8735946d5eb6af65c).

I do not like the `setImmediate()` approach because it feels like a code smell. So this object needs to be refactored to either replace the recursion with some flavor of simple iteration or the recursion needs to be implemented in such a way that it wont negatively impact the call stack or memory usage.

**Comment by medienoekonom** [comment]
it works. so i dont give a fu§! :)

**Comment by stevenbenner** [comment]
I'm inclined to agree.

It has been 8 years and I haven't felt the need to make this optimization yet, so I'm just going to close this issue.
